collections:
  Chana:
    output: true
    permalink: /:collection/:path
  Sahota:
    output: true
    permalink: /:collection/:path
  Rai:
    output: true
    permalink: /:collection/:path

defaults:
    - scope:
        path: ""
        type: Chana
      values:
          layout: tree
          colour: c66
    - scope:
        path: ""
        type: Rai
      values:
          layout: tree
          colour: 58b
    - scope:
        path: ""
        type: Matharu
      values:
          layout: tree
          colour: c67
    - scope:
        path: ""
        type: Sahota
      values:
          layout: tree
          colour: 57b
