#

collections:
    chana:
        output: true
        permalink: /:collection/:path

defaults:
    - scope:
        path: ""
        type: Chana
      values:
          layout: tree
    - scope:
        path: ""
        type: Rai
      values:
          layout: tree

#

#
