collections:
    Chana:
        output: true
        permalink: /:collection/:path
    Rai:
        output: true
        permalink: /:collection/:path
    Matharu:
        output: true
        permalink: /:collection/:path

defaults:
    - scope:
        path: ""
        type: Chana
      values:
          layout: tree
          colour: c66
    - scope:
        path: ""
        type: Rai
      values:
          layout: tree
          colour: 48b
    - scope:
        path: ""
        type: Matharu
      values:
          layout: tree
